export const LEGACY_MUSIC_PROMPT = 'Warm cinematic ambient, soft felt piano, gentle acoustic textures, spacious and slowly evolving, instrumental, understated documentary score';

// Reference scores from DrawnExplainers/sets/not-arbitrary, by the same author.
// Shared with Android through scripts/sync-android-prompts.ts.
export const musicInstruction = `EPISODE MUSIC DIRECTION:
When the response schema asks for musicPrompt, compose an original English Lyria prompt for THIS podcast's subject and requested storytelling style. It is production metadata, never spoken text. Do not put it, instrument descriptions, or music cues inside pairs.
Write 45–85 words of concrete musical direction, not a synopsis, playlist, composer name, or generic genre list. Choose one foreground instrument with a specific playing technique, one quiet supporting texture or low instrument, spacious pacing, and a vivid restrained mood grounded in this subject. Keep the arrangement sparse, with wide gaps between notes and a gentle, stable pulse or no percussion. Leave the speech frequencies and attention clear. No vocals, chants, strong melodic hooks, dramatic swells, drops, abrupt transitions, or a repeating tune that becomes tiring over a long episode.
Honor the listener's style: a folk story may suggest dry plucked wood and a low reed; comedy can be gently offbeat without becoming busy or cartoonish; scientific curiosity can be intimate and tactile rather than grand cinematic spectacle. These are examples, not fixed mappings. Vary the palette thoughtfully; do not default to piano for every subject or infer an instrument from the language being learned. Make the mood sustainable for a long unfolding conversation, not a timed cue sheet. Finish with explicit room for a speaking voice.
These successful documentary scores demonstrate specificity and restraint. Learn from their construction; write a new score for the actual topic rather than copying the closest example:
Chinese characters: "Sparse solo piano with felt hammers, unhurried, wide space between notes. Soft upright bass notes far back. Warm room tone, faint brushed cymbal texture. Contemplative study-room mood, gentle and curious, never sentimental. Instrumental only, no vocals, no strong melodic hook that competes with a speaking voice."
Card suits: "Sparse fingerpicked nylon-string guitar, unhurried, wide space between the notes. A low bass clarinet holding long quiet tones underneath. Faint dusty room tone, no percussion. Contemplative and curious, the patience of a print workshop. Instrumental only, no vocals, no strong melodic hook that competes with a speaking voice."
Chess pieces: "Sparse solo vibraphone with long decay, played very slowly, wide spacing between notes, low unhurried cello drone underneath, no melodic hook, no percussion, instrumental only, patient and thoughtful, room for a speaking voice"
Roman numerals: "Sparse solo marimba, soft mallets on wood, played very slowly with wide space between the notes and no repeating melody. A low bowed viola holding long quiet tones underneath. Faint dry room tone, like a workshop. Curious and patient, a little ancient, never grand or ceremonial. Instrumental only, no vocals, no drums, no melodic hook that competes with a speaking voice."
Once a music prompt is accepted, the same score continues throughout the episode. Do not write another musicPrompt when it is absent from the requested schema.`;
